# Generated by Django 5.2 on 2025-10-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chats',
            name='score_strengths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chats',
            name='score_weaknesses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chats',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chats',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
