# Generated by Django 5.2 on 2025-11-08 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chats_score_chats_score_strengths_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='score',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='score_strengths',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='score_weaknesses',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='chats',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
